app = "ibwt-ui"
primary_region = "iad"

[deploy]
release_command = "npx prisma db push"

[http_service]
auto_start_machines = true
auto_stop_machines = "stop"
force_https = true
internal_port = 3_000
min_machines_running = 1
processes = ["app"]

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 512
